"""empty message

Revision ID: 12032516e94b
Revises: 401351d52424
Create Date: 2021-08-26 22:22:24.460844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12032516e94b'
down_revision = '401351d52424'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(), nullable=True),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('date_out', sa.Date(), nullable=True),
    sa.Column('date_in', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['key'], ['keys.name'], ),
    sa.ForeignKeyConstraint(['user'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assignments')
    # ### end Alembic commands ###
